---
# Source: auditing/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-tools
  namespace: default
---
# Source: auditing/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devops-tools
  namespace: default
rules:
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ["get", "patch", "create", "update"]
---
# Source: auditing/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-tools
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devops-tools
subjects:
  - kind: ServiceAccount
    name: devops-tools
---
# Source: auditing/templates/deploiement.yaml
apiVersion: v1
kind: Service
metadata:
  name: devops-tools
  labels:
    app: devops-tools
    deployed: "devops-tools-6.4.2.638"
  namespace: default
spec:
  selector:
    app: devops-tools
  ports:
    - name: devops-tools
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
# Source: auditing/templates/deploiement.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-tools
  labels:
    app: devops-tools
    deployed: "devops-tools-6.4.2.638"
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-tools
  template:
    metadata:
      name: devops-tools
      labels:
        app: devops-tools
        deployed: "devops-tools-6.4.2.638"
        environment: dev
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/service-name: "devops-tools"
        consul.hashicorp.com/connect-service-port: "8000"
        consul.hashicorp.com/connect-service-upstreams: "readingSecrets-rs-PythonRulez:8001, dfetools:3000"
    spec:
      serviceAccountName: "devops-tools"
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: devops-tools
          image: adrienbarret/devops-tools
          imagePullPolicy: Always
          ports:
            - name: devops-tools
              containerPort: 8000
